import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.min.css'; // Importa los estilos de Bootstrap
import '../styles/globals.css'; // Opcional si tienes otros estilos personalizados

// Importa tus fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Asegúrate de que los estilos de Bootstrap estén listos en el <head> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
